### ISSUE TITLE
How to make first.

### ISSUE THREAD

**Issue by CompanionG** [linlin991229/kabuxiyou#1]
hello , i'm a fan of Kabuxiyou ,and i want to rebuild the game too.But i don;t know where to start. It seems you are working with that.Hope you can give me some suggestions.Thanks a lot!

**Comment by aojiaoxiaolinlin** [comment]
为啥你要用英语呀，哭死。qq:1589861957，细聊。这个仓库目前是用来反馈bug的。

**Comment by aojiaoxiaolinlin** [comment]
complete
